### ISSUE TITLE
ID Attribute: Inconsistent Naming Convention

### ISSUE THREAD

**Issue by tajmone** [tajmone/Sublime-PML#15]
There are inconsistencies between PMLC 1.4.0 and the documentation regarding the naming convention of ID attributes.

Currently Sublime PML is assuming that a valid ID must abide to the above mentioned RegEx pattern:

    [a-zA-Z][a-zA-Z0-9_]*

and that anything else is an error (and should be highlighted as `invalid`)

while carrying out some tests with PML 1.4.0, I've noticed that `pmlc` doesn't actually complaint if an identifier starts with a digit, and creates an HTML document without problems.

I need to know how to act on this discrepancy, and whether I should:

1. amend Sublime PML to accept as valid ID anything matching the pattern:

    ```
    [a-zA-Z0-9_]*
    ```

2. or whether future versions of `pmlc` will amend the current situation and enforce the `[a-zA-Z][a-zA-Z0-9_]*` pattern and reject as an error IDs starting with a digit.

For more info, see: pml-lang/user-manual#3

**Comment by pml-lang** [comment]
> There are inconsistencies between PMLC 1.4.0 and the documentation

Yes. It's a bug in the current PML parser, as explained in [another](https://github.com/pml-lang/user-manual/discussions/3#discussioncomment-707570) comment. The documentation is correct. The bug will be fixed in the new PML parser.

> Currently Sublime PML is assuming that a valid ID must abide to the above mentioned RegEx pattern `[a-zA-Z][a-zA-Z0-9_]*` and that anything else is an error (and should be highlighted as invalid)

Yes, that's the correct way to do it.

**Comment by tajmone** [comment]
Then everything is fine. When PML 2.0 will be released, Sublime PML will already be compliant. 

And in the meantime it will enforce idiomatic PML on its users by pointing out patterns that will soon be deprecated.
