### ISSUE TITLE
Migrating to PML 2.3.0/3.0.0

### ISSUE THREAD

**Issue by tajmone** [tajmone/Sublime-PML#31]
@pml-lang, I've now started a new dev branch for the package migration to PML 2.3.0/3.0.0:

https://github.com/tajmone/Sublime-PML/tree/pml-2.3.0-3.0.0

This branch basically picks up from the previous migration work to PML 2.3.0 but (as discussed via email) I will be dropping many features since the braking changes of the new PML 2 parsing system are better dealt with a fresh rewrite of the package.

# PML 3.0.0 ETA?

You didn't provide me with an ETA for the upcoming PML 3 release, but in any case I think the best approach right now is to focus on quickly migrating the package to support PML 2.3.0, and then deal with the breaking changes of PML 3 when it's finally out (so I can actually use it while working on the package).

That said, it's worth keeping track of the breaking changes of PML 3, and simply drop any elements that would require too much adaptation.

# Migration Roadmap

I was hoping to have the new package ready and released by the weekend, although I don't have a clear picture of how much work there's left toward this goal.

In any case, these are the repository documents that I'm using to track the migration work:

- [`SYNTAX_STATUS.md`][SYNTAX_STATUS.md] — the current migration-status document.
- [`SYNTAX_STATUS_OLD.md`][SYNTAX_STATUS_OLD.md] — the old package status from the latest public version (PML 1.5.0).
- [`PMLv2_MIGRATION.md`][PMLv2_MIGRATION.md] — the previous PML 2.3.0 migration dev notes, listing the done and pending changes (the TODOs might no longer apply now that I'm planning dropping features).

Right now the motto driving the update is _"Less is more"_ — in the past, I've ended up being trapped in a loop of ever-changing features, where before I could manage to update the package to the latest PML release a new release with breaking changes came about, invalidating my previous work.

One way or the other, this package ended up being stuck to PML 1.5.0; so if we want to catch up with the latest PML evolution, the best approach is to disentangle the package by dropping out any features which are preventing the update, and simply re-implement them later on (having a lesser package is better than having no usable package at all).

# Support Needed

I'd like to use this Issue thread to consult you and discuss any decision regarding the best strategies for the migration work — which nodes are worth keeping and which ones to drop, and so on.

Likewise, if you have any suggestions in that direction, please do bring them forth — your tips are important since you have the full vision of where PML 3 is going.

[PMLv2_MIGRATION.md]: https://github.com/tajmone/Sublime-PML/blob/pml-2.3.0-3.0.0/PMLv2_MIGRATION.md "Dev notes on migration from PML 1.5.0 to 2.2.0"
[SYNTAX_STATUS.md]: https://github.com/tajmone/Sublime-PML/blob/pml-2.3.0-3.0.0/SYNTAX_STATUS.md "Current package status info"
[SYNTAX_STATUS_OLD.md]: https://github.com/tajmone/Sublime-PML/blob/pml-2.3.0-3.0.0/SYNTAX_STATUS_OLD.md "Old package status info"

**Comment by pml-lang** [comment]
> I've now started a new dev branch for the package migration to PML 2.3.0/3.0.0

Great!

> ETA for the upcoming PML 3 release

Version 3 will probably be published next month.

> migrating the package to support PML 2.3.0, and then deal with the breaking changes of PML 3

As mentioned already in an email, there are just very minor _syntax_ changes from version 2.3.0 to 3.0.0. They are documented in the Changelog and pml_tags.json I sent you by email. Please let me know if you need any other information.

> "Less is more" ... having a lesser package is better than having no usable package at all

👍

**Comment by pml-lang** [comment]
If you want I can send you a link to a standalone executable (pmlc.exe) for a version 3.0.0_beta on Windows (not the final version that will be published).
I've tested this version with all nodes and different PML documents, and there are just two minor bugs (whitespace handling) I'm aware of.

**Comment by tajmone** [comment]
> If you want I can send you a link to a standalone executable (pmlc.exe) for a version 3.0.0_beta on Windows (not the final version that will be published).

That would be great, just to have a better idea of what's awaiting next.

Also, once the ST PML package is fixed I want to start work on the PML GUI, which I've been already looking into. Since PML introduces some command line changes, it would be great to have a prototype to work with, so I might even have the GUI tool ready when it comes out, since it would only require minor last-minute fixes (if any).

**Comment by pml-lang** [comment]
FYI: I've sent you an email with a link to PMLC 3 beta.

> I want to start work on the PML GUI

Great!
Please note: I would like to first discuss an idea with you. Will send you a message in the coming days.

**Comment by tajmone** [comment]
# Almost There!

@pml-lang, I've actually managed to salvage all the existing nodes and convert them to the new `(..)` attributes notation, and while doing so I'm also managing to automatically implement the `id` and HTML-Attributes attributes on those node that support them, since now attributes definitions are shared-context.

Of course, the current migration doesn't take into account lenient parsing rules for attributes (that's another story altogether, an headhake that I'll have to work on later one). But still, it's good to see that all the previous work can be salvaged in the migration process, so the syntax package won't feel like a bare-bones features.

Now I only have to mechanically apply the same changes to a few node that are still using the old notation, but it's merely a matter of applying the same pattern as for other nodes, so it's just a matter of time.

I think that by tonight the syntax should be fully migrated, as I had foreseen, but unfortunately this doesn't yet make the package ready for release since there's a lot of polishing work, updating of documents and package/repository settings that need to be dealt with before I can squash into `main` and create the first tagged release. These all require double checking, especially the documentation.

Due to the extreme heat here, I can't over work at the PC as long as planned. During the day, especially the afternoon, it's hard to work, but at night it's much more comfortable (unless excessively fatigued by the heat during the day).

So, maybe still a few days before the package is publicly available, but then it will be possible to install it from within the ST editor (provided one has Git installed) and it will self-update henceforth, which is the other major improvement, since before it had to be manually updated via Git.

After all then, the PML 3 release _will_ coincide with a PML editor package being available for end user, and although it's not fir a free editor it's still better than nothing (if we had invested energy on Atom, as I suggested, it would have been a waste of time now that Atom has reached its end-of-life).

So, be ready for the imminent installation of Sublime-PML! You'll then soon be able to use it in production and provide me feedback on how to improve it.

**Comment by pml-lang** [comment]
Great !!!

**Comment by tajmone** [comment]
# Package Published

@pml-lang, I've just created the first public release of Sublime PML.

If you could please try to install it following the new instructions provided here and let me know how it went (if you had installed a previous version via Git, you need to remove it by deleting its folder):

https://github.com/tajmone/Sublime-PML/blob/main/README.md#installation-instructions

Once I'll publish a package update, you should finally be able to confirm that self-updating works as expected. In the meantime, enjoy the updated package, and the tons of features that I had implemented but you never saw due to its self-updating failure in the past!

**Comment by tajmone** [comment]
# First Package Update

@pml-lang, I've just released Sublime PML [0.7.1], the first package update.

If you could please confirm the following:

1. When you launch ST the package is automatically updated.
2. After updating Sublime PML, a message about the new release is shown (i.e. a markdown document listing changes and new features).

Just wanted to make sure that package updates work correctly after following the (new) instructions on the main README.



[0.7.1]: https://github.com/tajmone/Sublime-PML/releases/tag/0.7.1 "Sublime PML 0.7.1 release page"

**Comment by pml-lang** [comment]
> When you launch ST the package is automatically updated.

Yes, the package was updated, because `v2022-08-03` is displayed under `Package control: List packages`. This is also the date of file `AppData\Roaming\Sublime Text 3\Installed Packages\Sublime-PML.sublime-package` on my PC.

> After updating Sublime PML, a message about the new release is shown (i.e. a markdown document listing changes and new features).

No message was shown. However, this might be because when I started ST, it re-started to install a new version of itself, and displayed a message related to changes in ST.

**Comment by tajmone** [comment]
> Yes, the package was updated

Great! Thanks for the confirmation and the time you took to verify via dates details,

> No message was shown. However, this might be because when I started ST, it re-started to install a new version of itself, and displayed a message related to changes in ST.

Maybe that, or maybe it's just because it's not being installed via the PackageControl official channel. Although Sublime PML is installed using PackageControl, the fact that it's being updated via Git might be the cause these update messages are ignored; and if that's the case then it's probably ignoring Git release tags and just pulling the `main` branch at each update check. 

Unfortunately the PackageControl documentation is not very clear on the differences about packages installed via Git (the docs are sort of fragmented and very terse). But we could do a simple test to verify this: next time I update `main` branch without creating a new release, I could insert a small change that can be detected from within the package, so you could tell me whether you're seeing that change (i.e. if it was updated regardless of release tags).

If these update messages are not shown to end users, there's no point for me to keep writing them — i.e. until the package is not added to the official channel. But I also need to known whether ST is just pulling the repository each time, because if that's the case then I need to be careful about what changes I apply to main (right now, I've been working on the assumption that the package gets updated only when there's a new release, but now I feat this might not be the case).

**Comment by pml-lang** [comment]
> I could insert a small change that can be detected from within the package, so you could tell me whether you're seeing that change

Ok. Good idea.

**Comment by tajmone** [comment]
# Update Tests Results

Today I've spent some time setting up a portable version of ST in order to test how the installation of Sublime PML via Git works in detail.

So far, all my tests seem to confirm that the package installation and updates process is not tied to tag releases but simply Git pulling the `main` branch head.

These were my tests so far:

- Installed Sublime PML and created a backup of the `Sublime-PML.sublime-package` installed package.
- Added to the repository a commit on `main` (6363db313a) that tweaked the `README.md` file, then (manually) checked for package updates:
    + PackageControl listed an available update for Sublime PML, showing the commit timestamps of the installed version and that of the update.
    + After updating I extracted the README file from the local package and diff-compared it with that of my previous backup: the changes from the latest commit on `main` were present if without a tagged release.


Because I've updated the package manually, I can't confirm 100% that the ST will auto-update the package without intervention.


## Update Message?

> No message was shown. However, this might be because when I started ST, it re-started to install a new version of itself, and displayed a message related to changes in ST.

Usually Sublime Text preserves all open files when it restarts, including unsaved ones, so I think that if the update message for `0.7.1` had been shown you would have seen it on restart.

Unfortunately, I won't be able to test this without creating a new tagged release.

I can confirm that I get the Sublime PML installation message when install it, but I didn't get that of `0.7.1`, which I believe should also have been shown (appended to the install message), but I'm not 100%.

But, in general, I think that tagged-releases might not be working with the Git repository installation, or maybe they are not working because I've omitted some configuration files in the repository. Hard to tell, the documentation is very vague when it comes to this type of installation. I should probably contact the author of Package Control for some help.

At this point, I need to know whether I should keep updating these update messages or not, because if they are not shown there's no point wasting time on them.

### On Tagged Releases

For the next package update (which is basically ready, but I wanted to carry out these tests before releasing it) I'll still create a tagged release and package message. But then, if we don't get to see the update message, I'll have to decide whether to drop just package messages or tagged release altogether — if the package is being updated based on `main` HEAD, what's the point of creating all these tagged releases during the Alpha stage?

I could simply update the package without creating releases; for end users, it would make no difference since they don't even known when the package is being updated or not, and need to refer to the repository to learn about new features.

If I stop using tagged releases (and delete the current ones) during the Alpha (and maybe even the Beta) stage, I would work much faster and the package would grow quicker (since I have limited free time). I doubt end users even care about releases and the CHANGELOG, and it's not as if there are many users right now. So, focusing on production speed might be best right now, and if tagged releases are not needed for ST updates, I should just drop them, so I don't have to update the CHANGELOG, tags, etc, and can work much faster: whenever a feature is ready, I merge it into `main`, and the package is updated.

I only need further confirmation that the updates work based on `main` (see following sections).


## Help Confirming Tagged Release Update

But maybe you can help me here, since you installed Sublime PML when it was first released (i.e. `0.7.0`), you might confirm to me whether the package was automatically updated to the newer `0.7.1` release by checking and confirming if these new features are available to you:

- **Title Sub-nodes** — any inline nodes within a document or chapter title should be properly highlighted in Sublime PML `>=0.7.1`. So, if you could check form me in ST whether the following lines are properly highlighted in a PML document, it would confirm whether the package self-updated or not:


    ```
    [ch [title Font Test [b Bold ] Text]
    ```

    If the `[b` tag is not colourized, then it means you're still using the initial Sublime PML release (`0.7.1`)

## Help Confirming `main` Branch Update

If the package is indeed updated, you could further check whether ST has updated it to the latest `main` commit, and not just the latest tagged release. To do that, you'd need to peek inside the installed Sublime PML package — the `Sublime-PML.sublime-package` file, which is just a zipped archive stored in ST `<data_path>/Installed Packages/` (See [Packages]).

Under Windows, that folder should be located at:

    %APPDATA%\Sublime Text 3\Installed Packages\

Once you've located the `Sublime-PML.sublime-package` file, open it with a Zip tool and extract the main `README.md` to check if the latest changes of commit 6363db313a are present or not — namely, line 62 should contain the `&#8984;` entity instead of `cmd` (among other changes):

```markdown
Open the Command Palette by pressing <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd> (Windows and Linux) or <kbd>&#8984;</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd> (Mac).
```

That would really help understand how ST is handling package updates. If you can find the above change in your local Sublime PML, then it means it was auto-updated to the latest `main` HEAD.





[Packages]: https://www.sublimetext.com/docs/packages.html#locations "Sublime Text documentation » Packages"

**Comment by pml-lang** [comment]
Results of my test:

There was no Sublime-PML update message when I opened ST.

> If the [b tag is not colourized

The `[b` tag _is_ colorized:
![ST_PML_test](https://user-images.githubusercontent.com/77769154/184085054-e13c8acd-0ea3-4a26-9340-8dd32068af84.png)

Hence, the package was updated.

Moreover the date of file
AppData\Roaming\Sublime Text 3\Installed Packages\Sublime-PML.sublime-package
shows 2022-08-11

> line 62 should contain the &#8984;

Yes, this line 62 in README.md:
    1. Open the Command Palette by pressing <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd> (Windows and Linux) or <kbd>&#8984;</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd> (Mac).

**Comment by tajmone** [comment]
> Results of my test:

Thanks a lot for taking the time and confirm these tests! (and the screenshots too, very cool).

This really helped me out. Now that I now that the package is updated whenever `main` branch is, I can take an entirely different approach to its development:

- **Delete previous tags/releases** — might re-introduce them when the package reaches v1.0.0, if we decide to submit it to the official Package Control channel.
- **Delete package update messages** (just keep the installation message) and no longer care about having to document each update under a specific version bump.
- **Create a CHANGELOG file** where I simply list changes by date, so end users can consult it to see what was added since they last used the package and read its documentation. Since package updates can't show messages with the version info, and updates occur silently in the background, providing a CHANGELOG is the only way to keep users informed about new features.
    + Add a new menu to quickly access the CHANGELOG:
        **Tools &gt; PML &gt;  What's New?**

The new development/update strategy changes entirely, becoming slimmer and easier to handle.

From now on, the `main` branch will only be updated when new commits on `dev` constitute a full changeset: each new feature is added as a single commit, and before merging all the documentation (Manual, README, CHANGELOG, etc.) is updated in order to ensure that all changes are properly mentioned and covered.

This ensures that package updates are delivered as meaningful change-sets — i.e. since the package is updated _every_ time there are new commits on `master` we should avoid updates that contain only changes to internal docs or other repo files that don't affect the final package (i.e. are export-excluded or irrelevant to its practical use), and also avoid that new features are introduced without being documented.

Ultimately, instead of relying on tags/releases for updates we rely on merge operations on `main` instead. Each merge results in a package update, regardless of the number of new commits. This means that any time we're happy with the status of the `dev` branch we simply have to merge it and its changes will be delivered to end users, which is not bad at all at the current Alpha stage, where versioning makes little sense.

Ok, now I'll start working on updating the repo docs, explaining how the (new) package updates system works, and getting rid of the tags/releases and update messages, then I'll add the new syntax updates that are ready and queued.

**Comment by tajmone** [comment]
# New Update System Done!

Ok, I've updated the repository according to the new package update policy, as discussed above. See the [CHANGELOG] for the details.

Next time you launch ST, you should get an update to Sublime PML that will result in a new menu to open the Changelog:

- Tools > PML > Sublime PML Changelog

This menu will help users keep track of new features, since we can't notify them about via package messages.



[CHANGELOG]: https://github.com/tajmone/Sublime-PML/blob/main/CHANGELOG.md

**Comment by pml-lang** [comment]
> Next time you launch ST, you should get an update to Sublime PML that will result in a new menu to open the Changelog

Yes, I confirm.

**Comment by tajmone** [comment]
# Migrated to PML 3.0.0!

@pml-lang, Sublime PML has already been updated to PML 3 now.

The new changes only affected the build systems, i.e. tweaking the command line invocation of PMLC. The rest was just bumping-up all references to PML version from 2.3.0 to 3.0.0.

**Comment by pml-lang** [comment]
> Sublime PML has already been updated to PML 3 now.

Wow! That was _fast_!
